---
title: "Quantitative Methods in Geography"
author: "Nicholas N. Nagle"
date: "October 8, 2014"
header-includes:
  \usepackage{tabu}
output: pdf_document
---

**Instructor:** Nicholas Nagle, Assistant Professor

Office: BGB 307

Office Hours: Thursday: 9-11

Email: nnagle@utk.edu

**Course Information**

**Lecture**

Time: Tu/Th: 11:10-12:25

Location: BGB 101

Office Hours: Thursday: 9-11 AM

**A note on office hours:**  I almost always receive unannounced walk-ins to my office, even if my door is closed.  So in addition to email, you may just knock and see if I’m available.  I will be in my office Mondays, Tuesdays and Thursdays this semester.  At other times, it is likely that I am at Oak Ridge National Laboratory and unavailable for office appointments.

**Lab**

Monday: 1:25-3:20 OR 3:35-5:30

Location: BGB 202


## Course Overview

This is a course about data analysis in geography.  We will look at how models and data are used to learn about our world.

This course if first and foremost about the science of data analysis in geography.  I have conceptual objectives for you: goals about how you should look at the world and data about the world, and I have technical objectives for you: techniques that you should be able to know about at the end of the course.

**Learning Outcomes**
 - Students will understand the concepts of location and variability, and be able to choose appropriate graphics to communicate these.
 - Students will be able to characterize hypothesis testing and how they are used in scientific investigations.
 - Students will be able to describe the difference between correlation and regression, how to explain regression output, and be able to identify its limitations in specific applications.
 - Students will be able to explain the complications to statistical analysis that are encountered by geographers.

**Guide to student success**
Beyond the obvious (come to class prepared, having completed the reading for that segment and completed lab assigments), the most important tip is to constantly self-assess your understanding by asking "Why is this material important?"  If, at any point, for any topic, you are unable to answer this question, then you need to ask questions in class until you understand.

**Methods of Instruction**
This course has lecture and computer lab components.  The lecture component will occasionally include question and answering, discussion, and individual and group problem solving.  The computer lab will introduce students to the R statistical software and allow students to explore techniques.  Lab exercises will often be discussed in lecture.


## Textbooks
**Required** Peter Rogerson, *Statistical Methods for Geographers*.  Sage Press. 2010.

Additional readings will be assigned in class as needed.  

## Required Computer Equipment
You will need to bring to lab either:

- Your own personal laptop computer (and power cord). I strongly urge you to install R on your personal computer at home, and to bring a laptop to lab if you have one.
- Or a USB “thumb” drive. I recommend a 4GB or larger USB drive.


## Grading
 - Lab assignments/Homework: 50%  Homework will be assigned during the lab sections.  Homework assignments are usually due one week after being assigned, however, some may have extended due dates.
 - Midterm exam:  25%
 - Final exam: 25%

## Participation and Attendance
Participation means *participation*, not simply being present.

This class goes a lot more smoothly when students take some control of it, by asking questions about the material and about other quantitative work they have seen elsewhere.  

I will not grade attendance.  I believe that it is a prerequisite of an acceptable grade.  If you fail to show up for class, I will likely\ *impute* that to a lack of concern about your grade, and I will be less likely to give you the benefit of the doubt should you need it.

## Grading Scale

Undergraduate | Graduate
--------------| -------------
A 93  | Content
A- 90 |  { }


## Weekly Schedule

\begin{tabular}{l c c c}
\hline \hline
$i=$ & Date & Topic & Rogerson\\ \hline
1 & Jan 8 & Introduction  \\ \hline
2 & Jan 13 & Fundamentals: Sample/Population \& Statistic/Parameter  & 2\\
 & Jan 15 & Distributions & 3\&4\\ \hline
3 & Jan 19 - MLK No lab &  \\
 & Jan 20 & & \\
 & Jan 22 & \\ \hline
4 & Jan 27 & Models \& Estimation& \\
 & Jan 29 & \\ \hline
5 & Feb 3 &  \\
 & Feb 5 & \\ \hline
6 & Feb 10 & Correlation \& Bivariate Regression & 7.1, 7.2, 7.6; 8\\
 & Feb 12 & \\ \hline
7 & Feb 17 & Hypothesis Testing & 5\\
 & Feb 19 & \\ \hline
8 & Feb 24 & Nonparametrics & 7.5\\
 & Feb 26 & Mid-term \\ \hline
9 & Mar 3 & Multivariate Regression \& ANOVA & 6.1, 6.2; 9.1-9.5 \\
 & Mar 5 & \\ \hline
10 & Mar 10 & Multivariate Regression: Confounding \\
 & Mar 12 & \\ \hline
11 & Mar 24 & Regression: Assumptions and Diagnostics 8.4\\
 & Mar 26 & \\ \hline
12 & Mar 31 & Nonlinear Regression \& Supervised classification & 9.6-9.8\\
 & Apr 2 &  \\ \hline
13 & Apr 7 & Intro to Spatial Statistics & 10 \& 11 \\
 & Apr 9 & \\ \hline
14 & Apr 14 & Intro to Time Series \\
 & Apr 16 & \\ \hline
15 & Apr 21 & AAG \\
 & Apr 23 & \\ \hline
N & & Finals!  \\ \hline \hline
\end{tabular}




## Additional Information
**No extra credit:**  As a policy of the Geography Department, extra work for credit is not allowed.

**Campus Civility Statement**
Civility is genuine respect and regard for others: politeness, consideration, tact, good manners, graciousness, cordiality, affability, amiability and courteousness. Civility enhances academic freedom and integrity, and is a prerequisite to the free exchange of ideas and knowledge in the learning community. Our community consists of students, faculty, staff, alumni, and campus visitors. Community members affect each other’s well-being and have a shared interest in creating and sustaining an environment where all community members and their points of view are valued and respected. Affirming the value of each member of the university community, the campus asks that all its members adhere to the principles of civility and community adopted by the campus: http://civility.utk.edu/.

**Academic Integrity**
“An essential feature of the University of Tennessee, Knoxville is a commitment to maintaining an atmosphere of intellectual integrity and academic honesty. As a student of the university, I pledge that I will neither knowingly give nor receive any inappropriate assistance in academic work, thus affirming my own personal commitment to honor and integrity.”

Students are responsible for the information in Hilltopics http://dos.utk.edu/hilltopics/ regarding the policies and procedures about plagiarism and other forms of student misconduct.

**Disabilities that Constrain Learning**
“Any student who feels he or she may need an accommodation based on the impact of a disability should contact the Office of Disability Services (ODS) at 865-974-6087 in 2227 Dunford Hall to document their eligibility for services. ODS will work with students and faculty to coordinate reasonable accommodations for students with documented disabilities.”

**YOUR ROLE IN IMPROVING TEACHING AND LEARNING THROUGH COURSE ASSESSMENT**
At UT, it is our collective responsibility to improve the state of teaching and learning. During the semester, you may be requested to assess aspects of this course either during class or at the completion of the class. You are encouraged to respond to these various forms of assessment as a means of continuing to improve the quality of the UT learning experience.


**KEY RESOURCES FOR STUDENTS:**

- Undergraduate Catalogs: http://catalog.utk.edu (Listing of academic programs, courses, and policies)
- Graduate Catalog: http://catalog.utk.edu/index.php?catoid=7/ 
- Hilltopics: http://dos.utk.edu/hilltopics (Campus and academic policies, procedures and standards of conduct)
- Course Timetable: https://bannerssb.utk.edu/kbanpr/bwckschd.p_disp_dyn_sched (Schedule of classes)
- Academic Planning: http://www.utk.edu/advising (Advising resources, course requirements, and major guides)
- Student Success Center: http://studentsuccess.utk.edu (Academic support resources)
- Library: http://www.lib.utk.edu (Access to library resources, databases, course reserves, and services)
- Career Services: http://career.utk.edu (Career counseling and resources; HIRE-A-VOL job search system)
